package config

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

// preserveEnv registers the env keys Load may overwrite so they are restored
// after the test (Load calls os.Setenv directly, bypassing t.Setenv tracking).
func preserveEnv(t *testing.T) {
	t.Helper()
	for _, k := range []string{
		"OPENLIST_URL", "OPENLIST_TOKEN", "OPENLIST_SRC_STORAGE",
		"OPENLIST_DST_STORAGE", "WATCH_DIRS", "SYNC_STATUS_DIR",
		"CLEANUP_AFTER_HOURS", "UPLOAD_CONCURRENCY", "STABILIZE_WAIT_SECONDS",
		"POLL_INTERVAL_SECONDS", "TASK_TIMEOUT_SECONDS", "LOG_LEVEL", "LOG_FILE",
		"UI_LISTEN", "CLEANUP_DRY_RUN", "OPENLIST_OVERWRITE",
		"TASKS_ENABLED", "ALLOWED_SOURCE_PREFIXES", "CLEANUP_INTERVAL_SECONDS",
	} {
		t.Setenv(k, os.Getenv(k))
	}
}

func fullForm(t *testing.T) FormValues {
	t.Helper()
	dir := t.TempDir()
	return FormValues{
		OpenListURL:            "http://openlist:5244",
		OpenListToken:          "new-token",
		OpenListSrcStorage:     "/local_media",
		OpenListDstStorage:     "/139yun_media",
		WatchDirs:              []string{dir},
		SyncStatusDir:          filepath.Join(dir, ".sync_status"),
		AllowedSourcePrefixes:  []string{dir},
		CleanupAfterHours:      72,
		CleanupIntervalSeconds: 3600,
		UploadConcurrency:      2,
		StabilizeWaitSeconds:   30,
		PollIntervalSeconds:    3,
		TaskTimeoutSeconds:     1800,
		LogLevel:               "info",
		UIListen:               ":8099",
	}
}

func TestMergeAndSave_UpdatesAndPreservesComments(t *testing.T) {
	preserveEnv(t)
	path := filepath.Join(t.TempDir(), "cloud-sync.yaml")
	existing := "# keep this header\n" +
		"openlist_url: \"http://old\"\n" +
		"openlist_token: \"secret\"\n" +
		"watch_dirs:\n  - /old/dir\n" +
		"# keep the concurrency comment\n" +
		"upload_concurrency: 9\n"
	if err := os.WriteFile(path, []byte(existing), 0o644); err != nil {
		t.Fatal(err)
	}

	v := fullForm(t)
	v.OpenListToken = "" // keep existing token
	v.OpenListURL = "http://new"

	if err := MergeAndSave(path, v); err != nil {
		t.Fatalf("MergeAndSave: %v", err)
	}
	out, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	s := string(out)
	for _, want := range []string{
		"# keep this header",
		"# keep the concurrency comment",
		"http://new",
		"secret",
		"upload_concurrency: 2",
		"cleanup_dry_run: false", // key absent before, added
	} {
		if !strings.Contains(s, want) {
			t.Errorf("merged yaml missing %q:\n%s", want, s)
		}
	}
	if strings.Contains(s, "/old/dir") {
		t.Errorf("watch_dirs not replaced:\n%s", s)
	}

	got, err := Load(path)
	if err != nil {
		t.Fatalf("Load merged: %v", err)
	}
	if got.OpenListURL != "http://new" || got.OpenListToken != "secret" {
		t.Errorf("loaded url/token = %q/%q", got.OpenListURL, got.OpenListToken)
	}
	if got.UploadConcurrency != 2 {
		t.Errorf("upload_concurrency = %d, want 2", got.UploadConcurrency)
	}
}

func TestMergeAndSave_TokenOverride(t *testing.T) {
	preserveEnv(t)
	path := filepath.Join(t.TempDir(), "cloud-sync.yaml")
	if err := os.WriteFile(path, []byte("openlist_token: \"old\"\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	v := fullForm(t)
	v.OpenListToken = "brand-new"
	if err := MergeAndSave(path, v); err != nil {
		t.Fatalf("MergeAndSave: %v", err)
	}
	got, err := Load(path)
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	if got.OpenListToken != "brand-new" {
		t.Errorf("token = %q, want brand-new", got.OpenListToken)
	}
}

func TestSaveRaw_ValidatesBeforeReplacing(t *testing.T) {
	preserveEnv(t)
	path := filepath.Join(t.TempDir(), "cloud-sync.yaml")
	if err := os.WriteFile(path, []byte("log_level: info\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	// Invalid (missing required keys) must fail and leave the file untouched.
	if err := SaveRaw(path, []byte("log_level: info\n")); err == nil {
		t.Fatal("SaveRaw(invalid) = nil, want error")
	}
	cur, _ := os.ReadFile(path)
	if string(cur) != "log_level: info\n" {
		t.Errorf("file changed after failed save: %q", cur)
	}

	// A valid document (generated by MergeAndSave) replaces the file.
	if err := MergeAndSave(path, fullForm(t)); err != nil {
		t.Fatalf("MergeAndSave: %v", err)
	}
	good, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if err := SaveRaw(path, good); err != nil {
		t.Fatalf("SaveRaw(valid): %v", err)
	}
	if _, err := Load(path); err != nil {
		t.Fatalf("Load saved: %v", err)
	}
}

func TestRender_ParsesAndHasComments(t *testing.T) {
	preserveEnv(t)
	dir := t.TempDir()
	cfg := &Config{
		OpenListURL: "http://openlist:5244", OpenListToken: "tok",
		SrcStorage: "/local_media", DstStorage: "/139yun_media",
		WatchDirs: []string{dir}, SyncStatusDir: filepath.Join(dir, ".sync_status"),
		AllowedPrefixes: []string{dir}, CleanupAfter: 72 * time.Hour,
		UploadConcurrency: 2, StabilizeWait: 30 * time.Second, PollInterval: 3 * time.Second,
		TaskTimeout: 1800 * time.Second, LogLevel: "info", UIListen: ":8099",
		CleanupInterval: 3600 * time.Second,
	}
	out, err := Render(cfg)
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	if !strings.Contains(string(out), "#") {
		t.Errorf("Render output has no comments:\n%s", out)
	}
	path := filepath.Join(t.TempDir(), "cloud-sync.yaml")
	if err := os.WriteFile(path, out, 0o644); err != nil {
		t.Fatal(err)
	}
	if _, err := Load(path); err != nil {
		t.Fatalf("Load(Render output): %v", err)
	}
}

func TestMergeAndSave_CleanupInterval(t *testing.T) {
	preserveEnv(t)
	path := filepath.Join(t.TempDir(), "cloud-sync.yaml")
	v := fullForm(t)
	v.CleanupIntervalSeconds = 600
	if err := MergeAndSave(path, v); err != nil {
		t.Fatalf("MergeAndSave: %v", err)
	}
	got, err := Load(path)
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	if got.CleanupInterval != 600*time.Second {
		t.Errorf("CleanupInterval = %v, want 600s", got.CleanupInterval)
	}
}
